### ISSUE TITLE
FireFox

### ISSUE THREAD

**Issue by webdobe** [ggingell/react-fullscreenable#3]
It appears the firefox uses psuedo fullscreen?  Is this true?

https://developer.mozilla.org/samples/domref/fullscreen.html

Works in both chrome and firefox on my machine.

However, when using react-fullscreenable.  It appears only chrome is working.  Is this a bug or am I missing something?

**Comment by ggingell** [comment]
Another good catch. It looks like this is a bug in the fullscreen polyfill. I have a pull requestion open that fixes in the main project. https://github.com/chrisdickinson/fullscreen/pull/12 will let you know when it's merged or if I have to publish the fork.

**Comment by ggingell** [comment]
Resolved in version 2.4.3
