### ISSUE TITLE
Unable to scroll in fullscreen

### ISSUE THREAD

**Issue by helfer** [ggingell/react-fullscreenable#4]
Thanks for this great component @ggingell! Here's a small issue I've run into:

I am unable to scroll in fullscreen if the content is overflowing. I can fix it in the developer tools by setting "overflow: auto" on the div that has witdh=100% and height=100%. Is this intentional or am I doing something wrong?

**Comment by ggingell** [comment]
You're doing it correctly. You can use that style rule on the main div or an immediate child: 
https://github.com/ggingell/react-fullscreenable/blob/master/example/demo.css#L37

The tough part about this component is that on some devices it requires some amount of CSS. If I inline too much of the CSS it becomes less flexible for consumers and more likely to causes issues if there is a major browser update. Sorry for the late response, I'm not sure how I missed the notification.

**Comment by helfer** [comment]
Hi @ggingell, thanks for getting back to me! I thought I tried adding that CSS rule, but I'll give it another try, thanks!
