### ISSUE TITLE
Doesn't work on mobile?

### ISSUE THREAD

**Issue by devinlovescode** [ggingell/react-fullscreenable#5]
I'm trying to build a mobile react web app and it won't go into full screen on my mobile phone's chrome or safari browser.

**Comment by ggingell** [comment]
Hey @devinlovescode what version of iOS are you seeing this issue? If you clone this repo and run `npm i`, and then `npm run start` does the demo page work on your device? Finally, if you can connect your device to a desktop and use Safari to inspect the mobile view are you seeing any exceptions/warnings in the console?
